#!/usr/bin/bash

echo "DROP DATABASE IF EXISTS hbnb_dev_db;" | sudo mysql
cat setup_mysql_dev.sql | sudo mysql
echo "quit" | HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db HBNB_TYPE_STORAGE=db ./console.py


